services:
  - type: web
    name: proyectowebxio
    runtime: static
    plan: free
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
    routes:
      - type: rewrite
        source: /
        destination: /placeholder-checkout-colores-liderlib-v7.html
